### ISSUE TITLE
TwitterRestClient.uploadMediaFromPath and all its variants fail with cryptic message...

### ISSUE THREAD

**Issue by edcastsachin** [DanielaSfregola/twitter4s#131]
Simple Media upload of a "png" file fails with a cryptic message...

`[info] Running SlimClient 
Unexpected type info AnnotatedType(TypeRefType(NoPrefixType,TypeSymbol(T, owner=0, flags=12100, info=33 ),List()),List(40))
[success] Total time: 4 s, completed Aug 16, 2017 10:21:24 AM
`

The following program has been tried with 5.0, 5.1 and also SNAPSHOT-5.2 version of twitter4s.

```
import com.danielasfregola.twitter4s.TwitterRestClient
import scala.concurrent.Await
import scala.concurrent.ExecutionContext.Implicits.global
import scala.util.{Failure, Success}

object SlimClient extends App {

  // TODO - Make sure to define your consumer and access tokens!
  val client = TwitterRestClient()

  //client.createTweet(status = "Slim Client using twitter4s - Now with a change")
  val image = "/boxes/edcast/guideme/socialmedia/twitter/gmloader/data/tourvideo.png"
  val result = for {
    upload <- client.uploadMediaFromPath(image)
    tweet <- client.createTweet(status = "Test with media", media_ids = Seq(upload.media_id))
  } yield tweet

  result.onComplete {
    case Success(tweet) => println(tweet.id)
    case Failure(ex) => println(ex.getMessage)
  }

}
```

**Comment by DanielaSfregola** [comment]
Hi @edcastsachin,
we'll have a look at it. Could you please provide the stack trace of the exception?

Thanks

**Comment by allantl** [comment]
I got the same issue when trying to run the above code, stack trace:
```
[error] (run-main-0) org.json4s.package$MappingException: Unexpected type info AnnotatedType(TypeRefType(NoPrefixType,TypeSymbol(T, owner=0, flags=12100, info=33 ),List()),List(40))
org.json4s.package$MappingException: Unexpected type info AnnotatedType(TypeRefType(NoPrefixType,TypeSymbol(T, owner=0, flags=12100, info=33 ),List()),List(40))
        at org.json4s.reflect.package$.fail(package.scala:95)
        at org.json4s.reflect.ScalaSigReader$.findPrimitive$1(ScalaSigReader.scala:112)
        at org.json4s.reflect.ScalaSigReader$.findArgType(ScalaSigReader.scala:117)
        at org.json4s.reflect.ScalaSigReader$.readConstructor(ScalaSigReader.scala:22)
        at org.json4s.reflect.Reflector$ClassDescriptorBuilder.ctorParamType(Reflector.scala:93)
        at org.json4s.reflect.Reflector$ClassDescriptorBuilder.$anonfun$ctorParamType$3(Reflector.scala:101)
        at org.json4s.reflect.Reflector$ClassDescriptorBuilder.ctorParamType(Reflector.scala:98)
        at org.json4s.reflect.Reflector$ClassDescriptorBuilder.$anonfun$createConstructorDescriptors$6(Reflector.scala:157)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
        at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:59)
        at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:52)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
        at scala.collection.TraversableLike.map(TraversableLike.scala:234)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
        at scala.collection.AbstractTraversable.map(Traversable.scala:104)
        at org.json4s.reflect.Reflector$ClassDescriptorBuilder.$anonfun$createConstructorDescriptors$3(Reflector.scala:142)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
        at scala.collection.mutable.ArraySeq.foreach(ArraySeq.scala:74)
        at scala.collection.TraversableLike.map(TraversableLike.scala:234)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
        at scala.collection.AbstractTraversable.map(Traversable.scala:104)
        at org.json4s.reflect.Reflector$ClassDescriptorBuilder.createConstructorDescriptors(Reflector.scala:136)
        at org.json4s.reflect.Reflector$ClassDescriptorBuilder.constructorsAndCompanion(Reflector.scala:121)
        at org.json4s.reflect.Reflector$ClassDescriptorBuilder.result(Reflector.scala:185)
        at org.json4s.reflect.Reflector$.createDescriptor(Reflector.scala:53)
        at org.json4s.reflect.Reflector$.$anonfun$describe$1(Reflector.scala:48)
        at org.json4s.reflect.package$Memo.apply(package.scala:36)
        at org.json4s.reflect.Reflector$.describe(Reflector.scala:48)
        at org.json4s.Extraction$.decomposeObject$1(Extraction.scala:118)
        at org.json4s.Extraction$.internalDecomposeWithBuilder(Extraction.scala:228)
        at org.json4s.Extraction$.addField$1(Extraction.scala:110)
        at org.json4s.Extraction$.decomposeObject$1(Extraction.scala:140)
        at org.json4s.Extraction$.internalDecomposeWithBuilder(Extraction.scala:228)
        at org.json4s.Extraction$.internalDecomposeWithBuilder(Extraction.scala:189)
        at org.json4s.Extraction$.addField$1(Extraction.scala:110)
        at org.json4s.Extraction$.decomposeObject$1(Extraction.scala:140)
        at org.json4s.Extraction$.internalDecomposeWithBuilder(Extraction.scala:228)
        at org.json4s.Extraction$.addField$1(Extraction.scala:110)
        at org.json4s.Extraction$.decomposeObject$1(Extraction.scala:140)
        at org.json4s.Extraction$.internalDecomposeWithBuilder(Extraction.scala:228)
        at org.json4s.Extraction$.addField$1(Extraction.scala:110)
        at org.json4s.Extraction$.decomposeObject$1(Extraction.scala:140)
        at org.json4s.Extraction$.internalDecomposeWithBuilder(Extraction.scala:228)
        at org.json4s.Extraction$.decomposeWithBuilder(Extraction.scala:64)
        at org.json4s.native.Serialization$.write(Serialization.scala:43)
        at org.json4s.native.Serialization$.write(Serialization.scala:37)
        at de.heikoseeberger.akkahttpjson4s.Json4sSupport.$anonfun$json4sMarshaller$1(Json4sSupport.scala:97)
        at akka.http.scaladsl.marshalling.Marshaller.$anonfun$compose$2(Marshaller.scala:73)
        at akka.http.scaladsl.marshalling.Marshaller$$anon$1.apply(Marshaller.scala:92)
        at akka.http.scaladsl.marshalling.Marshal.to(Marshal.scala:27)
        at akka.http.scaladsl.client.RequestBuilding$RequestBuilder.apply(RequestBuilding.scala:47)
        at com.danielasfregola.twitter4s.http.clients.OAuthClient$OAuthRequestBuilder.apply(OAuthClient.scala:62)
        at com.danielasfregola.twitter4s.http.clients.rest.media.TwitterMediaClient.appendMediaChunk(TwitterMediaClient.scala:130)
        at com.danielasfregola.twitter4s.http.clients.rest.media.TwitterMediaClient.$anonfun$appendMedia$1(TwitterMediaClient.scala:115)
        at com.danielasfregola.twitter4s.http.clients.rest.media.TwitterMediaClient.$anonfun$appendMedia$1$adapted(TwitterMediaClient.scala:115)
        at com.danielasfregola.twitter4s.util.MediaReader.$anonfun$processAsChunks$1(MediaReader.scala:14)
        at scala.collection.immutable.Stream.map(Stream.scala:415)
        at com.danielasfregola.twitter4s.util.MediaReader.processAsChunks(MediaReader.scala:14)
        at com.danielasfregola.twitter4s.http.clients.rest.media.TwitterMediaClient.appendMedia(TwitterMediaClient.scala:116)
        at com.danielasfregola.twitter4s.http.clients.rest.media.TwitterMediaClient.$anonfun$uploadMediaFromInputStream$2(TwitterMediaClient.scala:98)
        at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:302)
        at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:415)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by allantl** [comment]
After some debugging, I found out that this is related to akka/akka-http#541.

**Comment by DanielaSfregola** [comment]
Thanks @allantl, for the extra info...I'll try to have a look!

In the meanwhile, PRs are always welcome :)

Cheers,
D.
