### ISSUE TITLE
`PipelineException: No usable value for search_metadata` on empty search result

### ISSUE THREAD

**Issue by loicknuchel** [DanielaSfregola/twitter4s#17]
When I perform a search and there is no results I get the error : 
```
[PipelineException: No usable value for search_metadata
No usable value for next_results
Did not find value which can be converted into java.lang.String]
```

My Play action : 
```scala
def test() = Action.async { implicit req =>
  new TwitterClient().searchTweet(
    query = "qsfomq",
    count = 10,
    include_entities = true,
    result_type = ResultType.Recent).map { res =>
    Ok("ok")
  }
}
```

And the full stacktrace : 
```
play.api.Application$$anon$1: Execution exception[[PipelineException: No usable value for search_metadata
No usable value for next_results
Did not find value which can be converted into java.lang.String]]
	at play.api.Application$class.handleError(Application.scala:296) ~[play_2.11-2.3.10.jar:2.3.10]
	at play.api.DefaultApplication.handleError(Application.scala:402) [play_2.11-2.3.10.jar:2.3.10]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$14$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:205) [play_2.11-2.3.10.jar:2.3.10]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$14$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:202) [play_2.11-2.3.10.jar:2.3.10]
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36) [scala-library-2.11.7.jar:na]
Caused by: spray.httpx.PipelineException: No usable value for search_metadata
No usable value for next_results
Did not find value which can be converted into java.lang.String
	at spray.httpx.ResponseTransformation$$anonfun$unmarshal$1.apply(ResponseTransformation.scala:36) ~[spray-httpx_2.11-1.3.3.jar:na]
	at spray.httpx.ResponseTransformation$$anonfun$unmarshal$1.apply(ResponseTransformation.scala:31) ~[spray-httpx_2.11-1.3.3.jar:na]
	at spray.httpx.TransformerPipelineSupport$WithTransformation.$tilde$greater(TransformerPipelineSupport.scala:33) ~[spray-httpx_2.11-1.3.3.jar:na]
	at com.danielasfregola.twitter4s.http.clients.OAuthClient$$anonfun$unmarshalResponse$1.apply(OAuthClient.scala:34) ~[twitter4s_2.11-0.2.jar:0.2]
	at com.danielasfregola.twitter4s.http.clients.OAuthClient$$anonfun$unmarshalResponse$1.apply(OAuthClient.scala:32) ~[twitter4s_2.11-0.2.jar:0.2]
Caused by: org.json4s.package$MappingException: No usable value for search_metadata
No usable value for next_results
Did not find value which can be converted into java.lang.String
	at org.json4s.reflect.package$.fail(package.scala:96) ~[json4s-core_2.11-3.2.11.jar:3.2.11]
	at org.json4s.Extraction$ClassInstanceBuilder.org$json4s$Extraction$ClassInstanceBuilder$$buildCtorArg(Extraction.scala:462) ~[json4s-core_2.11-3.2.11.jar:3.2.11]
	at org.json4s.Extraction$ClassInstanceBuilder$$anonfun$14.apply(Extraction.scala:482) ~[json4s-core_2.11-3.2.11.jar:3.2.11]
	at org.json4s.Extraction$ClassInstanceBuilder$$anonfun$14.apply(Extraction.scala:482) ~[json4s-core_2.11-3.2.11.jar:3.2.11]
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245) ~[scala-library-2.11.7.jar:na]
Caused by: org.json4s.package$MappingException: No usable value for next_results
Did not find value which can be converted into java.lang.String
	at org.json4s.reflect.package$.fail(package.scala:96) ~[json4s-core_2.11-3.2.11.jar:3.2.11]
	at org.json4s.Extraction$ClassInstanceBuilder.org$json4s$Extraction$ClassInstanceBuilder$$buildCtorArg(Extraction.scala:462) ~[json4s-core_2.11-3.2.11.jar:3.2.11]
	at org.json4s.Extraction$ClassInstanceBuilder$$anonfun$14.apply(Extraction.scala:482) ~[json4s-core_2.11-3.2.11.jar:3.2.11]
	at org.json4s.Extraction$ClassInstanceBuilder$$anonfun$14.apply(Extraction.scala:482) ~[json4s-core_2.11-3.2.11.jar:3.2.11]
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245) ~[scala-library-2.11.7.jar:na]
Caused by: org.json4s.package$MappingException: Did not find value which can be converted into java.lang.String
	at org.json4s.Extraction$.convert(Extraction.scala:603) ~[json4s-core_2.11-3.2.11.jar:3.2.11]
	at org.json4s.Extraction$.extract(Extraction.scala:350) ~[json4s-core_2.11-3.2.11.jar:3.2.11]
	at org.json4s.Extraction$ClassInstanceBuilder.org$json4s$Extraction$ClassInstanceBuilder$$buildCtorArg(Extraction.scala:450) ~[json4s-core_2.11-3.2.11.jar:3.2.11]
	at org.json4s.Extraction$ClassInstanceBuilder$$anonfun$14.apply(Extraction.scala:482) ~[json4s-core_2.11-3.2.11.jar:3.2.11]
	at org.json4s.Extraction$ClassInstanceBuilder$$anonfun$14.apply(Extraction.scala:482) ~[json4s-core_2.11-3.2.11.jar:3.2.11]
```

**Comment by DanielaSfregola** [comment]
Thank you for raising this bug! We'll fix it asap

**Comment by loicknuchel** [comment]
Thanks for your quick answer :)
I've got the same for some other methods...
Maybe you can check twitter response, they seems to be different when there is no data...

**Comment by DanielaSfregola** [comment]
Will do, actually you are correct: no data is an edge case that I forgot to analyse! cheers

**Comment by DanielaSfregola** [comment]
Hi Loic,
I have done a patch release with a fix for the bug you raised.
Upgrading to version 0.2.1 should fix your problem.

Cheers and thank you again for flagging the issue!
Daniela

**Comment by loicknuchel** [comment]
Hi @DanielaSfregola, awesome !
Thanks for your quick fix !

**Comment by MingmingYue** [comment]
"org.json4s" % "json4s-mongo_2.11" % "3.6.1" 
This problem will still occur when fetching data from mongodb 。
