### ISSUE TITLE
Use of external Actor System in the library

### ISSUE THREAD

**Issue by shiv4nsh** [DanielaSfregola/twitter4s#185]
When I am trying to create a TwitterRestClient it makes its own ActorSystem and I have already made one actor system for my app. Is there a way in which the internal actor system can be override i.e it will use the external actor system that is provided if not then it can create one for itself.

**Comment by DanielaSfregola** [comment]
Hi @shiv4nsh,
with the current implementation this is not possible. 

This has been done intentionally to simplify the use of the library and making sure operations like stopping the actor system when needed (not too soon, not too late) are done automatically without leaks in the API: the first version of twitter4s was using an external Actor System, causing lots of errors related to the actor system management - see #140 for more info on it.

That being said, I am open to the discussion.....why would you want to use an external actor system? what is your business scenario?

Cheers,
D.

**Comment by shiv4nsh** [comment]
I am trying to build an application where I am building my own Actor System,(pretty basic Scenario).
I run this app on my laptop it works ok ! But When I deploy it on Heroku , within seconds it crashes with this error:
`2018-01-07T15:44:08.192109+00:00 app[web.1]: Uncaught error from thread [twitter4s-rest-bea6326a-21bf-41ec-a239-2de7c58431ab-akka.actor.default-dispatcher-4]: unable to create new native thread, Uncaught error from thread [twitter4s-rest-bea6326a-21bf-41ec-a239-2de7c58431ab-akka.actor.default-dispatcher-2]: unable to create new native thread, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for for ActorSystem[twitter4s-rest-bea6326a-21bf-41ec-a239-2de7c58431ab]

2018-01-07T15:44:08.220463+00:00 app[web.1]: Uncaught error from thread [twitter4s-rest-85e32954-8c17-4b50-8305-0834cecf21e4-akka.actor.default-dispatcher-6]: unable to create new native thread, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for for ActorSystem[Uncaught error from thread [twitter4s-rest-dfcac4fe-c31f-49a3-844c-6e7702007ad6-akka.actor.default-dispatcher-3]: unable to create new native thread, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled forUncaught error from thread [twitter4s-rest-6cc560ee-a047-4891-b68a-d265d4e2e9fd-akka.actor.default-dispatcher-3 for ActorSystem[twitter4s-rest-dfcac4fe-c31f-49a3-844c-6e7702007ad6]

2018-01-07T15:44:08.220648+00:00 app[web.1]: java.lang.OutOfMemoryError: unable to create new native thread

2018-01-07T15:44:08.220843+00:00 app[web.1]: 	at java.lang.Thread.start0(Native Method)

2018-01-07T15:44:08.220968+00:00 app[web.1]: 	at java.lang.Thread.start(Thread.java:717)

2018-01-07T15:44:08.221043+00:00 app[web.1]: 	at java.util.concurrent.ForkJoinPool.createWorker(ForkJoinPool.java:1486)

2018-01-07T15:44:08.221500+00:00 app[web.1]: 	at java.util.concurrent.ForkJoinPool.tryAddWorker(ForkJoinPool.java:1517)

2018-01-07T15:44:08.221582+00:00 app[web.1]: 	at java.util.concurrent.ForkJoinPool.signalWork(ForkJoinPool.java:1634)

2018-01-07T15:44:08.221871+00:00 app[web.1]: 	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1733)

2018-01-07T15:44:08.221941+00:00 app[web.1]: 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1691)

2018-01-07T15:44:08.222137+00:00 app[web.1]: 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

2018-01-07T15:44:08.222846+00:00 app[web.1]: Uncaught error from thread [twitter4s-rest-85e32954-8c17-4b50-8305-0834cecf21e4-akka.actor.default-dispatcher-2]: unable to create new native thread, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for for ActorSystem[twitter4s-rest-85e32954-8c17-4b50-8305-0834cecf21e4]

2018-01-07T15:44:08.222952+00:00 app[web.1]: java.lang.OutOfMemoryError: unable to create new native thread

2018-01-07T15:44:08.223120+00:00 app[web.1]: 	at java.lang.Thread.start0(Native Method)

2018-01-07T15:44:08.223197+00:00 app[web.1]: 	at java.lang.Thread.start(Thread.java:717)

2018-01-07T15:44:08.223273+00:00 app[web.1]: 	at java.util.concurrent.ForkJoinPool.createWorker(ForkJoinPool.java:1486)

2018-01-07T15:44:08.223369+00:00 app[web.1]: 	at java.util.concurrent.ForkJoinPool.tryAddWorker(ForkJoinPool.java:1517)

2018-01-07T15:44:08.223447+00:00 app[web.1]: 	at java.util.concurrent.ForkJoinPool.signalWork(ForkJoinPool.java:1634)

2018-01-07T15:44:08.223523+00:00 app[web.1]: 	at java.util.concurrent.ForkJoinPool.externalPush(ForkJoinPool.java:2414)

2018-01-07T15:44:08.223625+00:00 app[web.1]: 	at java.util.concurrent.ForkJoinPool.execute(ForkJoinPool.java:2630)

2018-01-07T15:44:08.223711+00:00 app[web.1]: 	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinPool.execute(AbstractDispatcher.scala:401)

2018-01-07T15:44:08.223791+00:00 app[web.1]: 	at akka.dispatch.ExecutorServiceDelegate.execute(ThreadPoolBuilder.scala:211)

2018-01-07T15:44:08.223863+00:00 app[web.1]: 	at akka.dispatch.ExecutorServiceDelegate.execute$(ThreadPoolBuilder.scala:211)

2018-01-07T15:44:08.223946+00:00 app[web.1]: 	at akka.dispatch.Dispatcher$LazyExecutorServiceDelegate.execute(Dispatcher.scala:39)

2018-01-07T15:44:08.224020+00:00 app[web.1]: 	at akka.dispatch.Dispatcher.registerForExecution(Dispatcher.scala:115)

2018-01-07T15:44:08.224094+00:00 app[web.1]: 	at akka.dispatch.MessageDispatcher.attach(AbstractDispatcher.scala:133)

2018-01-07T15:44:08.224170+00:00 app[web.1]: 	at akka.actor.dungeon.Dispatch.start(Dispatch.scala:100)

2018-01-07T15:44:08.224246+00:00 app[web.1]: 	at akka.actor.dungeon.Dispatch.start$(Dispatch.scala:98)

2018-01-07T15:44:08.224329+00:00 app[web.1]: 	at akka.actor.ActorCell.start(ActorCell.scala:374)

2018-01-07T15:44:08.224402+00:00 app[web.1]: 	at akka.actor.ActorCell.start(ActorCell.scala:374)

2018-01-07T15:44:08.224477+00:00 app[web.1]: 	at akka.actor.RepointableActorRef.point(RepointableActorRef.scala:107)

2018-01-07T15:44:08.224558+00:00 app[web.1]: 	at akka.actor.ActorCell.handleSupervise(ActorCell.scala:625)

2018-01-07T15:44:08.224644+00:00 app[web.1]: 	at akka.actor.ActorCell.supervise(ActorCell.scala:617)

2018-01-07T15:44:08.224718+00:00 app[web.1]: 	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:468)

2018-01-07T15:44:08.224802+00:00 app[web.1]: 	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:483)

2018-01-07T15:44:08.231534+00:00 app[web.1]: 	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)[ERROR] [SECURITY][01/07/2018 15:44:08.229] [twitter4s-rest-dfcac4fe-c31f-49a3-844c-6e7702007ad6-akka.actor.default-dispatcher-3] [akka.actor.ActorSystemImpl(twitter4s-rest-dfcac4fe-c31f-49a3-844c-6e7702007ad6)] Uncaught error from thread [twitter4s-rest-dfcac4fe-c31f-49a3-844c-6e7702007ad6-akka.actor.default-dispatcher-3]: unable to create new native thread, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[twitter4s-rest-dfcac4fe-c31f-49a3-844c-6e7702007ad6]

2018-01-07T15:44:08.231538+00:00 app[web.1]: java.lang.OutOfMemoryError: unable to create new native thread

2018-01-07T15:44:08.231539+00:00 app[web.1]: 	at java.lang.Thread.start0(Native Method)

2018-01-07T15:44:08.231540+00:00 app[web.1]: 	at java.lang.Thread.start(Thread.java:717)

2018-01-07T15:44:08.231542+00:00 app[web.1]: 	at java.util.concurrent.ForkJoinPool.createWorker(ForkJoinPool.java:1486)

2018-01-07T15:44:08.231543+00:00 app[web.1]: 	at java.util.concurrent.ForkJoinPool.tryAddWorker(ForkJoinPool.java:1517)

2018-01-07T15:44:08.231544+00:00 app[web.1]: 	at java.util.concurrent.ForkJoinPool.signalWork(ForkJoinPool.java:1634)

2018-01-07T15:44:08.231545+00:00 app[web.1]: 	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1733)

2018-01-07T15:44:08.231546+00:00 app[web.1]: 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1691)

2018-01-07T15:44:08.231548+00:00 app[web.1]: 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

2018-01-07T15:44:08.231553+00:00 app[web.1]: 

2018-01-07T15:44:08.241659+00:00 app[web.1]: 

2018-01-07T15:44:08.241716+00:00 app[web.1]: 	at akka.dispatch.Mailbox.run(Mailbox.scala:223)

2018-01-07T15:44:08.241823+00:00 app[web.1]: 	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)

2018-01-07T15:44:08.241893+00:00 app[web.1]: 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)

2018-01-07T15:44:08.241950+00:00 app[web.1]: 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)

2018-01-07T15:44:08.242096+00:00 app[web.1]: 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)

2018-01-07T15:44:08.242101+00:00 app[web.1]: 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

2018-01-07T15:44:08.242666+00:00 app[web.1]: shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for for ActorSystem[twitter4s-rest-bea6326a-21bf-41ec-a239-2de7c58431ab]

2018-01-07T15:44:08.242745+00:00 app[web.1]: java.lang.OutOfMemoryError: unable to create new native thread`

Hence I investigated and found out that multiple actor system is being made and twitter4s tries to create more actors and fails and crashes the application. Is there any way in which I can overcome this ? 
Or maybe use your actor system somehow ?

**Comment by DanielaSfregola** [comment]
Which version of twitter4s are you using?

**Comment by shiv4nsh** [comment]
I am using : 5.4-Snapshot

**Comment by DanielaSfregola** [comment]
Ok thanks! 

Every time twitter4s does a request, it should create an actor system, it should use it to perform the request and then close it. Unfortunately, we do need to create an actor system because of the way akka http works.

Twitter4s shouldn't leave any actor system hanging around - every time it creates one it should always close it. Unless there is a bug where twitter4s forgets to close an actor system - i.e.: the actor systems number grows with time and never goes down - I would assume that your application needs more resources to run.
 
Also, have you tried doing some JVM profiling to see where the threads are used? Running some profiling on your laptop could be enough to see why you are using so many threads.

**Comment by shiv4nsh** [comment]
>  twitter4s does a request, it should create an actor system, it should use it to perform the request and then close it

Don't you think it is wrong . As it will create and close everytime it fires a request ?
Akka Docs states that Creation of Actor System is a very heavy process ?

**Comment by DanielaSfregola** [comment]
I agree, creating a new Actor System is expensive -- but this is how it currently works.

We could change the implementation and have 1 internal actor system shared for all the requests, but then there are other issues like the followings: when do you create it? when do you stop it? or does it run forever?

I am absolutely open to discussions and, in particular, PRs are always welcome.

**Comment by DanielaSfregola** [comment]
You could argue that is you use an external actor system you do not have any of these problems: the consumer of the API takes care of creating it and destroying it...

Maybe we could support both....?

**Comment by DanielaSfregola** [comment]
Eureka! I have an idea -- thanks for the useful brainstorming and discussion!

I'll see if I can find some time next week to write down some notes - feel free to give it a try...PRs are always welcome!

**Comment by smrnv** [comment]
Hi, I think we can have implicit abstract method of ActorSystem type in the TwitterSearchClient. So we can create instance of TwitterSearchClient and pass external actor system in it, or instantiate an actor system in it.

**Comment by DanielaSfregola** [comment]
Change released in `twitter4s 5.5`: we now have 1 actor system per client, rather than 1 actor system started and stopped per request.

You can now attach an existing actor system using the following: 
```scala
TwitterRestClient.withActorSystem(mySystem)
```

Also, you can shutdown an actor system associated to a client with the function `shutdown`
