### ISSUE TITLE
sbt-git not working on Windows machines

### ISSUE THREAD

**Issue by broilogabriel** [DanielaSfregola/twitter4s#199]
Just for the record in case someone face the same issue. 

I'm having problems to build the project with the following setup: Intellij 2017.3.4 + Windows 10

It seems the issue is caused due some problems with sbt-git (https://github.com/sbt/sbt-git/issues/100). The stacktrace displayed in Intellij is:

```
Error while importing sbt project:

[info] Loading settings from idea.sbt ...
[info] Loading global plugins from C:\Users\broilogabriel\.sbt\1.0\plugins
[info] Loading settings from plugins.sbt ...
[info] Loading project definition from D:\dev\workspace\twitter4s\project
[info] Updating {file:/D:/dev/workspace/twitter4s/project/}twitter4s-build...
[info] Done updating.
[warn] Found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[warn] 	* org.eclipse.jgit:org.eclipse.jgit:4.5.0.201609210915-r is selected over 3.7.0.201502260915-r
[warn] 	    +- com.typesafe.sbt:sbt-git:0.9.3 (scalaVersion=2.12, sbtVersion=1.0) (depends on 3.7.0.201502260915-r)
[warn] 	    +- org.scoverage:sbt-coveralls:1.2.2 (scalaVersion=2.12, sbtVersion=1.0) (depends on 3.7.0.201502260915-r)
[warn] Run 'evicted' to see detailed eviction warnings
[info] Loading settings from build.sbt,sonatype.sbt ...
13:33:06.048 [pool-6-thread-4] ERROR org.eclipse.jgit.util.FS - Caught exception in FS.readPipe()
java.io.IOException: Cannot run program "git" (in directory "\usr\bin"): CreateProcess error=2, The system cannot find the file specified
at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048) ~[?:1.8.0_112]
at org.eclipse.jgit.util.FS.readPipe(FS.java:500) ~[?:?]
at org.eclipse.jgit.util.FS.readPipe(FS.java:464) ~[?:?]
at org.eclipse.jgit.util.FS.discoverGitSystemConfig(FS.java:613) ~[?:?]
at org.eclipse.jgit.util.FS.getGitSystemConfig(FS.java:653) ~[?:?]
at org.eclipse.jgit.util.SystemReader$Default.openSystemConfig(SystemReader.java:97) ~[?:?]
at org.eclipse.jgit.internal.storage.file.FileRepository.<init>(FileRepository.java:176) ~[?:?]
at org.eclipse.jgit.storage.file.FileRepositoryBuilder.build(FileRepositoryBuilder.java:92) ~[?:?]
at com.typesafe.sbt.git.JGit$.apply(JGit.scala:118) ~[?:?]
at com.typesafe.sbt.git.DefaultReadableGit.<init>(ReadableGit.scala:35) ~[?:?]
at com.typesafe.sbt.SbtGit$.$anonfun$buildSettings$1(SbtGit.scala:112) ~[?:?]
at scala.Function1.$anonfun$compose$1(Function1.scala:44) ~[scala-library.jar:1.0.0]
at sbt.internal.util.EvaluateSettings$MixedNode.evaluate0(INode.scala:214) ~[collections_2.12-1.0.4.jar:1.0.3]
at sbt.internal.util.EvaluateSettings$INode.evaluate(INode.scala:159) ~[collections_2.12-1.0.4.jar:1.0.3]
at sbt.internal.util.EvaluateSettings.$anonfun$submitEvaluate$1(INode.scala:82) ~[collections_2.12-1.0.4.jar:1.0.3]
at sbt.internal.util.EvaluateSettings.sbt$internal$util$EvaluateSettings$$run0(INode.scala:93) ~[collections_2.12-1.0.4.jar:1.0.3]
at sbt.internal.util.EvaluateSettings$$anon$3.run(INode.scala:89) ~[collections_2.12-1.0.4.jar:1.0.3]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_112]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_112]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
at java.lang.ProcessImpl.create(Native Method) ~[?:1.8.0_112]
at java.lang.ProcessImpl.<init>(ProcessImpl.java:386) ~[?:1.8.0_112]
at java.lang.ProcessImpl.start(ProcessImpl.java:137) ~[?:1.8.0_112]
at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029) ~[?:1.8.0_112]
... 19 more
[error] java.io.IOException: Cannot run program "git": CreateProcess error=2, The system cannot find the file specified
[error] 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
[error] 	at scala.sys.process.ProcessBuilderImpl$Simple.run(ProcessBuilderImpl.scala:71)
[error] 	at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.lineStream(ProcessBuilderImpl.scala:143)
[error] 	at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.lineStream_$bang(ProcessBuilderImpl.scala:111)
[error] 	at scala.sys.process.ProcessBuilder.lines_$bang(ProcessBuilder.scala:202)
[error] 	at scala.sys.process.ProcessBuilder.lines_$bang$(ProcessBuilder.scala:202)
[error] 	at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.lines_$bang(ProcessBuilderImpl.scala:87)
[error] 	at com.typesafe.sbt.SbtGit$.$anonfun$buildSettings$21(SbtGit.scala:138)
[error] 	at sbt.internal.util.Init$Value.$anonfun$apply$3(Settings.scala:804)
[error] 	at sbt.internal.util.EvaluateSettings.$anonfun$constant$1(INode.scala:197)
[error] 	at sbt.internal.util.EvaluateSettings$MixedNode.evaluate0(INode.scala:214)
[error] 	at sbt.internal.util.EvaluateSettings$INode.evaluate(INode.scala:159)
[error] 	at sbt.internal.util.EvaluateSettings.$anonfun$submitEvaluate$1(INode.scala:82)
[error] 	at sbt.internal.util.EvaluateSettings.sbt$internal$util$EvaluateSettings$$run0(INode.scala:93)
[error] 	at sbt.internal.util.EvaluateSettings$$anon$3.run(INode.scala:89)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error] 	at java.lang.Thread.run(Thread.java:745)
[error] Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
[error] 	at java.lang.ProcessImpl.create(Native Method)
[error] 	at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
[error] 	at java.lang.ProcessImpl.start(ProcessImpl.java:137)
[error] 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
[error] 	at scala.sys.process.ProcessBuilderImpl$Simple.run(ProcessBuilderImpl.scala:71)
[error] 	at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.lineStream(ProcessBuilderImpl.scala:143)
[error] 	at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.lineStream_$bang(ProcessBuilderImpl.scala:111)
[error] 	at scala.sys.process.ProcessBuilder.lines_$bang(ProcessBuilder.scala:202)
[error] 	at scala.sys.process.ProcessBuilder.lines_$bang$(ProcessBuilder.scala:202)
[error] 	at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.lines_$bang(ProcessBuilderImpl.scala:87)
[error] 	at com.typesafe.sbt.SbtGit$.$anonfun$buildSettings$21(SbtGit.scala:138)
[error] 	at sbt.internal.util.Init$Value.$anonfun$apply$3(Settings.scala:804)
[error] 	at sbt.internal.util.EvaluateSettings.$anonfun$constant$1(INode.scala:197)
[error] 	at sbt.internal.util.EvaluateSettings$MixedNode.evaluate0(INode.scala:214)
[error] 	at sbt.internal.util.EvaluateSettings$INode.evaluate(INode.scala:159)
[error] 	at sbt.internal.util.EvaluateSettings.$anonfun$submitEvaluate$1(INode.scala:82)
[error] 	at sbt.internal.util.EvaluateSettings.sbt$internal$util$EvaluateSettings$$run0(INode.scala:93)
[error] 	at sbt.internal.util.EvaluateSettings$$anon$3.run(INode.scala:89)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error] 	at java.lang.Thread.run(Thread.java:745)
[error] java.io.IOException: Cannot run program "git": CreateProcess error=2, The system cannot find the file specified
[error] Use 'last' for the full log.
Invalid response.
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=384M; support was removed in 8.0
```

To be able to work I disabled the plugin in my local since I have no choice of OS for now, I'll try to investigate further later.

**Comment by DanielaSfregola** [comment]
Thanks @broilogabriel for reporting the issue!
