### ISSUE TITLE
AbstractMethodError when initializing a Twitter RestClient

### ISSUE THREAD

**Issue by MikeyCald** [DanielaSfregola/twitter4s#224]
Reached a massive block when initializing a Rest Client inside of a Spark-job.

Exception in thread "main" java.lang.AbstractMethodError: com.danielasfregola.twitter4s.http.serializers.JsonSupport$$anon$1.org$json4s$DefaultFormats$_setter_$strict_$eq(Z)V
	at org.json4s.DefaultFormats$class.$init$(Formats.scala:329)
	at com.danielasfregola.twitter4s.http.serializers.JsonSupport$$anon$1.<init>(JsonSupport.scala:21)
	at com.danielasfregola.twitter4s.http.serializers.JsonSupport$class.$init$(JsonSupport.scala:21)
	at com.danielasfregola.twitter4s.http.clients.rest.RestClient.<init>(RestClient.scala:15)
	at com.danielasfregola.twitter4s.TwitterRestClient.<init>(TwitterRestClient.scala:37)
	at com.danielasfregola.twitter4s.TwitterRestClient$.apply(TwitterRestClient.scala:71)
	at TwitterKafkaStream$.main(TwitterKafkaStream.scala:20)
	at TwitterKafkaStream.main(TwitterKafkaStream.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:879)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:197)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:227)

**Comment by MikeyCald** [comment]
Problem resolved , a json4s version conflict was present. My Uber Jar included Spark 2.3.0 which includes json4s:3.2.11. Solved by shading with assembly plugin.

assemblyShadeRules in assembly := Seq(
  ShadeRule.rename("org.json4s.**" -> "shaded.json4s.@1").inAll
)

**Comment by DanielaSfregola** [comment]
Hi @MikeyCald,
I am glad you solved it!

Closing the ticket
