### ISSUE TITLE
Rate Information expected but not found

### ISSUE THREAD

**Issue by akiomik** [DanielaSfregola/twitter4s#228]
Hi, I encountered the following error:

```
com.danielasfregola.twitter4s.exceptions.TwitterException: [500 Internal Server Error] Rate Information expected but not found.

Please report it at https://github.com/DanielaSfregola/twitter4s/issues/new
Headers names were: cache-control, content-disposition, date, expires, last-modified, pragma, server, set-cookie, set-cookie, set-cookie, status, strict-transport-security, x-access-level, x-connection-hash, x-content-type-options, x-frame-options, x-response-time, x-transaction, x-twitter-response-tags, x-xss-protection (500)
        at com.danielasfregola.twitter4s.exceptions.TwitterException$.apply(TwitterException.scala:32)
        at com.danielasfregola.twitter4s.entities.RateLimit$$anonfun$extractHeaderValue$1$3.apply(RateLimit.scala:28)
        at com.danielasfregola.twitter4s.entities.RateLimit$$anonfun$extractHeaderValue$1$3.apply(RateLimit.scala:28)
        at scala.Option.getOrElse(Option.scala:121)
        at com.danielasfregola.twitter4s.entities.RateLimit$.extractHeaderValue$1(RateLimit.scala:28)
        at com.danielasfregola.twitter4s.entities.RateLimit$.apply(RateLimit.scala:30)
        at com.danielasfregola.twitter4s.http.clients.rest.RestClient$$anonfun$4.apply(RestClient.scala:75)
        at com.danielasfregola.twitter4s.http.clients.rest.RestClient$$anonfun$4.apply(RestClient.scala:74)
        at com.danielasfregola.twitter4s.http.clients.CommonClient$class.unmarshal(CommonClient.scala:34)
        at com.danielasfregola.twitter4s.http.clients.rest.RestClient.unmarshal(RestClient.scala:14)
com.danielasfregola.twitter4s.exceptions.TwitterException: [500 Internal Server Error] Rate Information expected but not found.

Please report it at https://github.com/DanielaSfregola/twitter4s/issues/new
Headers names were: cache-control, content-disposition, date, expires, last-modified, pragma, server, set-cookie, set-cookie, set-cookie, status, strict-transport-security, x-access-level, x-connection-hash, x-content-type-options, x-frame-options, x-response-time, x-transaction, x-twitter-response-tags, x-xss-protection (500)
  at com.danielasfregola.twitter4s.exceptions.TwitterException$.apply(TwitterException.scala:32)
  at com.danielasfregola.twitter4s.entities.RateLimit$$anonfun$extractHeaderValue$1$3.apply(RateLimit.scala:28)
  at com.danielasfregola.twitter4s.entities.RateLimit$$anonfun$extractHeaderValue$1$3.apply(RateLimit.scala:28)
  at scala.Option.getOrElse(Option.scala:121)
  at com.danielasfregola.twitter4s.entities.RateLimit$.extractHeaderValue$1(RateLimit.scala:28)
  at com.danielasfregola.twitter4s.entities.RateLimit$.apply(RateLimit.scala:30)
  at com.danielasfregola.twitter4s.http.clients.rest.RestClient$$anonfun$4.apply(RestClient.scala:75)
  at com.danielasfregola.twitter4s.http.clients.rest.RestClient$$anonfun$4.apply(RestClient.scala:74)
  at com.danielasfregola.twitter4s.http.clients.CommonClient$class.unmarshal(CommonClient.scala:34)
  at com.danielasfregola.twitter4s.http.clients.rest.RestClient.unmarshal(RestClient.scala:14)
  at com.danielasfregola.twitter4s.http.clients.Client$$anonfun$sendAndReceive$1.apply(Client.scala:28)
  at com.danielasfregola.twitter4s.http.clients.Client$$anonfun$sendAndReceive$1.apply(Client.scala:28)
  at akka.stream.impl.fusing.MapAsync$$anon$24.onPush(Ops.scala:1169)
  at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:747)
  at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:649)
  at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:471)
  at akka.stream.impl.fusing.GraphInterpreterShell.receive(ActorGraphInterpreter.scala:410)
  at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:603)
  at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:618)
  at akka.actor.Actor$class.aroundReceive(Actor.scala:502)
  at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:529)
  at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
  at akka.actor.ActorCell.invoke(ActorCell.scala:495)
  at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
  at akka.dispatch.Mailbox.run(Mailbox.scala:224)
  at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
  at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
  at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
  at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
  at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

My scala version is 2.11.7, and twitter4s version is 5.3.

**Comment by DanielaSfregola** [comment]
Closing this as duplicate of https://github.com/DanielaSfregola/twitter4s/issues/236
