### ISSUE TITLE
is it possible to deal with RateLimit in some way?

### ISSUE THREAD

**Issue by iharh** [DanielaSfregola/twitter4s#79]
is it possible to deal with RateLimit in some way?

[INFO] [01/02/2017 20:18:37.005] [twitter4s-rest-akka.actor.default-dispatcher-2] [ActorSystem(twitter4s-rest)] GET https://api.twitter.com/1.1/search/tweets.json?count=100&include_entities=true&lang=es&q=android&result_type=recent (429 Too Many Requests) | 1082ms
com.danielasfregola.twitter4s.exceptions.TwitterException: [429 Too Many Requests] Rate limit exceeded (88)
	at com.danielasfregola.twitter4s.http.clients.Client$$anonfun$unmarshalResponse$1.apply(Client.scala:53)
	at com.danielasfregola.twitter4s.http.clients.Client$$anonfun$unmarshalResponse$1.apply(Client.scala:46)
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:237)
	at scala.util.Try$.apply(Try.scala:192)
	at scala.util.Success.map(Try.scala:237)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.processBatch$1(BatchingExecutor.scala:67)
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:82)
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:59)
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:59)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at akka.dispatch.BatchingExecutor$Batch.run(BatchingExecutor.scala:58)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by DanielaSfregola** [comment]
Hi @iharh , have a look at this page from the twitter dev documentation with a few tips around mitigating the rate limit issue: https://dev.twitter.com/rest/public/rate-limiting.

In my experience, most of the time switching to the use of the streaming api is the way of solving rate limit issues -- but it really depends on the type of the application you are building.

Cheers,
Daniela

**Comment by DanielaSfregola** [comment]
Closing this issue, feel free to reopen it if needed.

D.

**Comment by iharh** [comment]
Thank you, Daniela, for the link. I decided to go another way first - check "X-Rate-Limit..." HTTP headers for the REST API...

**Comment by DanielaSfregola** [comment]
mmm....interesting! Feel free to let me know if this is something that we should support -- PRs are always welcome ;)

**Comment by iharh** [comment]
I'm going to check headers myself, but, in general, you can better catch/process/rethrow exceptions at at com.danielasfregola.twitter4s.http.clients.Client, called by ForkJoinExecutor, if that is possible at all.

**Comment by iharh** [comment]
I've just started to look at the way to extract TwitterSearch response headers. Do you have any existing way/sample to do this using existing REST API (TwitterSearchClient-like-way) ?

**Comment by DanielaSfregola** [comment]
I am afraid I don't -- at present this is something that we do not do yet

**Comment by DanielaSfregola** [comment]
Let me create a ticket for it!

**Comment by iharh** [comment]
Thank you, Daniela. I've just also realized that TwitterSearchClient is just a one of a fixed-size-set of traits and it is impossible to create/mix a new one without rewriting existing code.

**Comment by DanielaSfregola** [comment]
Ticket created: https://github.com/DanielaSfregola/twitter4s/issues/80

**Comment by DanielaSfregola** [comment]
Rate Limits support is now available in twitter4s 5.0

**Comment by iharh** [comment]
Thank you, Daniela
